### PR TITLE
Finalize backend

### LINKED ISSUE #5: Create a API for frontend
This API basically integrates images from all other sources and return to the frontend requests.

### LINKED ISSUE #15: Create route to serve images from Yandex image
Child issue of #5

### LINKED ISSUE #28: Clean up the code
The current backend code was written in a rushed manner due to the deadlines so it is not very clean and of bad quality. Let's refactor it after #26 is merged.

### LINKED ISSUE #31: The image URL field is not correct
Related: #28 

Currently, the API use `path` for the URL of the image. This came up because I was dealing with the downloaded files, and within a computer we would say *path* to a file and not link or URL. However, since it's incorrect and unintuitive to say so, we should change the name of the field. I would like to change it to `image_url`.

### PR DESCRIPTION
**Pull request by dinhanhx**
⠀

### CODE REVIEW

**Comment by dinhanhx** [comment]
@Huy-Ngo so I have tried to merge branches at local machines. I ran the server stuff. It worked for all kaggle, isic, yandex, wikimedia. 
This comment is meant to tell you that when branches merged into `main`, things __doesn't__ break.

### kaggle
image
### isic
image
### yandex
image
### wikimedia
image

**Comment by Huy-Ngo** [comment]
@dinhanhx You didn't pull from Quang's branch. The yandex module is missing here.

**Comment by dinhanhx** [comment]
> @dinhanhx You didn't pull from Quang's branch. The yandex module is missing here.

fixed Yandex module is already in branch `main`

**Comment by Huy-Ngo** [comment]
It makes it hard for local testing. The next time you do this (as it, doing any kind of project in collaboration with someone else) make sure your new branch has all the feature needed.

**Comment by dinhanhx** [comment]
> It makes it hard for local testing. The next time you do this make sure your new branch has all the feature needed.

Okay. I agree it was bad move.

**Comment by Huy-Ngo** [comment]
Please add data.json to .gitignore.

**Comment by dinhanhx** [comment]
> Please add data.json to .gitignore.

Added to be ignored.

**Review by Huy-Ngo — APPROVED** [review]
Your code look good. It just lacks functionality, which I added, so please also review that.

**Comment by dinhanhx** [comment]
> Your code look good. It just lacks functionality, which I added, so please also review that.

I have pulled it down and ran flask stuff. It works.

**Pull request merged**
